module.exports = {
    NamedBlock: { nodes:[] },
    Block: { nodes:[] },
    Filter: { attrs:[] },
    Tag: { block:true },
    Case: { block:true },
    When: { block:true },
    Code: { block:true },
    Mixin: { block:true },
    InterpolatedTag: { block:true },
    While: { block:true },
    Each: { block:true, alternate:true },
    Conditional: { consequent:true, alternate:true },
    Include: { block:true, file:true },
    Extends: { file:true },
    RawInclude: { filters:[], file:true },
    Attrs: false,
    BlockComment: false,
    Comment: false,
    Doctype: false,
    IncludeFilter: false,
    MixinBlock: false,
    YieldBlock: false,
    Text: false,
    FileReference: { ast:true }
};